# Generated by Django 3.0.7 on 2020-06-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200623_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
